#!/usr/bin/env bash

# Setting env to skip redundant commands
export RUNNING_INSTALLER=1

# Install dependencies
yay --noconfirm

yay -S --needed --noconfirm \
    vim \
    neovim \
    tmux \
    fzf \
    ripgrep \
    curl \
    wget \
    unzip \
    xclip \
    zsh \
    gettext \
    gum \
    ghostty \
    fastfetch

INSTALLABLE=$(gum choose --no-limit --header "What do you wish to install?" "Hyprland" "PHP" "Docker" "Composer" "Symfony")

INSTALL=($(echo "$INSTALLABLE" | tr ',' '\n'))

for value in "${INSTALL[@]}"
do
  ./scripts/install-${value,,}.sh
done

if [ ! -d "$HOME/code/setup-tmp" ]; then
    gum log --structured --time="DateTime" --level info "Creating setup-tmp folder"

    mkdir -p ~/code/setup-tmp
fi

# Install Oh-My-Zsh and Starship if not installed
if [ ! -f "$HOME/.config/starship.toml" ]; then
    gum log --structured --time="DateTime" --level info "Setting up zsh and Starship"

    # Switch from bash to zsh
    chsh -s $(which zsh)

    git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions

    # Install Starship
        gum log --structured --time="DateTime" --level info "Installing Starship"

        cd $HOME/code/setup-tmp/
	curl -sS https://starship.rs/install.sh | sh
fi

# Install PHPActor (used in Neovim)
if [ ! -f "$HOME/.local/bin/phpactor" ]; then
    gum log --structured --time="DateTime" --level info "Installing/updating PHPActor"

    curl -Lo phpactor.phar https://github.com/phpactor/phpactor/releases/latest/download/phpactor.phar
    chmod a+x phpactor.phar
    mv phpactor.phar ~/.local/bin/phpactor
fi

if [ ! -d "$HOME/.fonts" ]; then
    echo ">> Creating .fonts folder..."
    mkdir -p ~/.fonts
fi

if [ ! -f "$HOME/.fonts/JetBrainsMonoNLNerdFont-Thin.ttf" ]; then
    # Setup fonts (from NerdFonts.com)
    echo ">> Downloading JetBrainsMono font from nerdfonts.com..."

    cd ~/.fonts/
    wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/JetBrainsMono.zip
    unzip JetBrainsMono.zip
    rm \
        JetBrainsMono.zip \
        OFL.txt \
        README.md
fi

# Node Version Manager
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash

if [ -d "$HOME/code/setup-tmp" ]; then
    echo ">> Removing setup-tmp folder..."
    sudo rm -rf "$HOME/code/setup-tmp"
fi

unset RUNNING_INSTALLER
